server:
  port: 8098

spring:
  application:
    name: user
  datasource:
    url: jdbc:mariadb://58.250.74.99:3306/mb_user?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root-password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis-plus日志:控制台输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #驼峰命名转换
  mapper-locations: classpath:mappers/*.xml  #控制台日志配置，mybatis-plus打印sql

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进EurekaServer默认为true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:8099/eureka  #注册地址
  instance:
    instance-id: user
    prefer-ip-address: true  #访问路径可以显示IP地址

ribbon:
  eureka:
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

