server:
  port: 8084

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://47.106.217.8:3306/mb_user?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shanxi_password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis-plus日志:控制台输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #驼峰命名转换
  mapper-locations: classpath:mappers/*.xml  #控制台日志配置，mybatis-plus打印sql

